# config/settings.yaml

database:
  url: "sqlite:///argo_chat.db"
  echo: false
  pool_size: 5
  max_overflow: 10
  timeout: 30

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/argo_system.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5

data_ingestion:
  supported_parameters:
    - "TEMP"
    - "PSAL"
    - "PRES"
    - "DOXY"
    - "CHLA"
    - "NITRATE"
    - "PH_IN_SITU_TOTAL"
  netcdf_extensions:
    - ".nc"
    - ".nc4"
  max_file_size_mb: 100
  quality_threshold: 70.0
  auto_cleanup_days: 365
  chunk_size: 1000

visualization:
  default_theme: "plotly_white"
  color_scales:
    temperature: "thermal"
    salinity: "haline"
    oxygen: "oxy"
    chlorophyll: "algae"
    nitrate: "matter"
    quality: "viridis"
  map_settings:
    default_zoom: 4
    cluster_threshold: 100
    tile_provider: "OpenStreetMap"
  plot_settings:
    default_width: 1200
    default_height: 800
    animation_duration: 500

nlp:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  similarity_threshold: 0.7
  max_results: 50
  cache_size: 1000
  cache_ttl: 3600
  enable_spell_check: true
  max_query_length: 500

api:
  host: "localhost"
  port: 8000
  debug: false
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8501"
  rate_limit_per_minute: 60
  enable_swagger: true

security:
  api_key_required: false
  allowed_file_types:
    - ".nc"
    - ".nc4"
    - ".zip"
  max_upload_size_mb: 100
  enable_encryption: false

performance:
  max_workers: 4
  batch_size: 100
  cache_ttl: 3600
  enable_compression: true
  query_timeout: 30

regions:
  indian_ocean:
    lat: [0, 30]
    lon: [40, 120]
  arabian_sea:
    lat: [10, 25]
    lon: [50, 75]
  bay_of_bengal:
    lat: [10, 25]
    lon: [80, 100]
  global:
    lat: [-90, 90]
    lon: [-180, 180]

quality_control:
  temperature_range: [-2, 40]
  salinity_range: [0, 40]
  pressure_range: [0, 6000]
  spike_threshold: 3.0
  gradient_threshold: 0.5
  enable_auto_qc: true